### ISSUE TITLE
[Error] chapter 14 docker file do not work properly on M1 Macbook

### ISSUE THREAD

**Issue by lih0905** [BasPH/data-pipelines-with-apache-airflow#57]
On Macbook Pro M1 Max, after running `docker-compose up -d`, the following error occured on port 8083 and 8082.

```
Traceback (most recent call last):

  File "app.py", line 4, in <module>

    from flask import Flask, render_template

  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 14, in <module>

    from jinja2 import escape

ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.7/site-packages/jinja2/__init__.py)

Traceback (most recent call last):

  File "app.py", line 4, in <module>

    from flask import Flask, render_template

  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 14, in <module>

    from jinja2 import escape

ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.7/site-packages/jinja2/__init__.py)
```

Also, 'minio_init-1' and 'initdb-adduser-1' are remained as 'EXITED(0)'.

**Comment by AlyElashram** [comment]
You can change the requirements.txt I mentioned this in the newest issue I opened. Check it out.
