### ISSUE TITLE
Chapter 3 manning-airflow/events_api Docker image problem

### ISSUE THREAD

**Issue by vasilypu** [BasPH/data-pipelines-with-apache-airflow#66]
Traceback (most recent call last):
  File "/app.py", line 8, in <module>
    from flask import Flask, jsonify, request
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/site-packages/jinja2/__init__.py)

**Comment by scndel** [comment]
Fixed in #61

**Comment by scndel** [comment]
Fixed in #61

**Comment by vasilypu** [comment]
I know how to fix it 
but docker image and github code still old
in requirementa.txt  
flask==1.1.2

**Comment by vasilypu** [comment]
**error:**
2024-01-17 18:34:53 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/site-packages/werkzeug/urls.py)

**Fixed by  modifying Dockerfile in docker/events-api:**

FROM python:3.8-slim

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt && rm -f /tmp/requirements.txt
**RUN pip uninstall -y Werkzeug && pip install Werkzeug==2.3.6**

COPY app.py /

EXPOSE 5000

ENTRYPOINT ["python"]
CMD ["/app.py"]
